master:
  push:
    - cacheFrom: .orange-ci.cache
      stages:
        - name: install
          script: tnpm install
        - name: dist
          script: tnpm run dist
        - name: list changed
          type: git:changeList
          options:
            changed: changed.txt
            deleted: deleted.txt
        # - name: eslint changed
        #   script: cat changed.txt | grep -e '\.(j|t)s$' | xargs -I {file} tnpm run eslint -- {file}
        # - name: test
        #   script: tnpm test
        - name: deploy
          type: orange-ci:transfer
          options:
            dist: /
            verbose: false
            to: /data/core_service
            ips:
              - 9.134.54.30
            after: pm2 restart core_server
  merge_request:
    - cacheFrom: .orange-ci.cache
      stages:
        - name: install
          script: tnpm install
        # - name: commit lint
        #   type: git:commitLint
        #   options:
        #     cli: tnpm run commitlint
        - name: list changed
          type: git:changeList
          options:
            changed: changed.txt
            deleted: deleted.txt
        # - name: eslint changed
        #   script: cat changed.txt | grep -e '\.(j|t)s$' | xargs -I {file} tnpm run eslint -- {file}
        # - name: test
        #   script: tnpm test
  tag_push:
    - stages:
        - name: changelog
          type: git:changeLog
          options:
            filename: CHANGELOG.md
            target: master
## 测试环境
dev:
  push:
    - cacheFrom: .orange-ci.cache
      stages:
        - name: install
          script: tnpm install
        - name: dist
          script: tnpm run dist
        - name: list changed
          type: git:changeList
          options:
            changed: changed.txt
            deleted: deleted.txt
        # - name: eslint changed
        #   script: cat changed.txt | grep -e '\.(j|t)s$' | xargs -I {file} tnpm run eslint -- {file}
        # - name: test
        #   script: tnpm test
        - name: deploy
          type: orange-ci:transfer
          options:
            dist: /
            verbose: false
            to: /data/core_service
            ips:
              - 9.134.32.201
            after: rm -r /data/core_service/node_modules/canvas && cp -rf /data/canvas /data/core_service/node_modules/canvas && pm2 restart core_server
  merge_request:
    - cacheFrom: .orange-ci.cache
      stages:
        - name: install
          script: tnpm install
        # - name: commit lint
        #   type: git:commitLint
        #   options:
        #     cli: tnpm run commitlint
        - name: list changed
          type: git:changeList
          options:
            changed: changed.txt
            deleted: deleted.txt
        # - name: eslint changed
        #   script: cat changed.txt | grep -e '\.(j|t)s$' | xargs -I {file} tnpm run eslint -- {file}
        # - name: test
        #   script: tnpm test
  tag_push:
    - stages:
        - name: changelog
          type: git:changeLog
          options:
            filename: CHANGELOG.md
            target: master
