module.exports = {
    map: [
        // 布局类
        'display',
        // 'boxOrient',
        // 'boxPack',
        // 'boxAlign',
        "flexDirection",
        "alignItems",
        "justifyContent",
        "flex",
        'width',
        //'height',
        'minHeight',
        'marginTop',
        'marginRight',
        'marginBottom',
        'marginLeft',
        'paddingTop',
        'top',
        'right',
        'bottom',
        'left',
        // // 属性类
        "zIndex",
        "backgroundImage",
        "backgroundColor",
        "backgroundSize",
        "backgroundRepeat",
        "color",
        "fontFamily",
        "fontSize",
        "position",
        "filter",
        "border",
        "boxSizing",
        "borderRadius",
        "overflow",
        "textOverflow",
        // "boxFlex",
        "textAlign",
        "whiteSpace",
        "lineHeight",
        "opacity"
    ]
}